from typing import Generator

from sqlalchemy import MetaData, create_engine, event
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import settings

# Deterministic constraint names (docs/modules/database_transaction_integrity.md
# #1/#3) -- matches the fk_<table>_<column>_<referred_table> style already
# used by hand for a few explicitly-named constraints, so autogenerated
# migrations and this project's own naming agree, and an unnamed
# constraint can always be targeted by a later migration (see 0010).
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

IS_SQLITE = settings.DATABASE_URL.startswith("sqlite")
connect_args = {"check_same_thread": False} if IS_SQLITE else {}
engine = create_engine(settings.DATABASE_URL, connect_args=connect_args)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

if IS_SQLITE:
    # SQLite ignores FOREIGN KEY constraints unless this pragma is set on
    # every connection -- without it, every ForeignKey() in these models
    # is declared but silently unenforced (docs/modules/database_transaction_integrity.md
    # #2/#8), so local dev/tests could pass while relying on referential
    # integrity that MySQL (this project's one supported production
    # database) enforces but SQLite quietly wouldn't have.
    @event.listens_for(engine, "connect")
    def _enable_sqlite_foreign_keys(dbapi_connection, connection_record) -> None:  # noqa: ANN001
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def get_db() -> Generator[Session, None, None]:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def savepoint(db: Session):
    """`db.begin_nested()` that is safe on SQLite too -- use it for any
    insert-and-retry that must not disturb the rest of the transaction.

    MySQL always runs a SAVEPOINT inside the open transaction. SQLite's
    Python driver (legacy mode) only opens a transaction at the first
    write, so a SAVEPOINT issued first would itself become the
    transaction and its RELEASE would commit -- a later failure in the
    same request could then no longer roll that insert back. Opening the
    transaction explicitly first keeps SQLite behaving like MySQL."""
    if IS_SQLITE:
        connection = db.connection()
        if not connection.connection.dbapi_connection.in_transaction:
            connection.exec_driver_sql("BEGIN")
    return db.begin_nested()
