import re
from dataclasses import dataclass


@dataclass(frozen=True)
class IdFormat:
    """One prefix+digit-count shape, shared by every entity that needs a
    human-readable reference id -- Quotation (QXXXXXX), Order (OXXXXXX),
    User (XXXXX), Product (PRXXXX), Material (MXXXX)
    (docs/modules/common_validation.md). Owns only the *shape*: which
    number comes next is the owning module's business (its own row
    count, a dedicated sequence, whatever fits that table) -- this never
    touches a database."""

    prefix: str
    digits: int

    @property
    def pattern(self) -> re.Pattern[str]:
        return re.compile(rf"^{re.escape(self.prefix)}\d{{{self.digits}}}$")

    @property
    def example(self) -> str:
        return f"{self.prefix}{'X' * self.digits}"

    def validate(self, value: str) -> str:
        if not self.pattern.match(value):
            raise ValueError(f"must match the format {self.example}")
        return value

    def format(self, sequence: int) -> str:
        maximum = 10**self.digits - 1
        if not (1 <= sequence <= maximum):
            raise ValueError(f"sequence must be between 1 and {maximum}")
        return f"{self.prefix}{sequence:0{self.digits}d}"


QUOTATION_ID = IdFormat(prefix="Q", digits=6)
ORDER_ID = IdFormat(prefix="O", digits=6)
# Purchase Order numbering is YY5NNNN, generated by
# app/services/purchase_order_service.generate_po_number -- not this
# primitive, which has no year-reset concept (docs/audit/RFQ_AUDIT.md
# #2). RFQ (YY3NNNN) and Purchase Order Payment (YY7NNNN) use the same
# shape via their own small generators for the same reason.
USER_ID = IdFormat(prefix="", digits=5)

# Every Phase 2 master's own code -- explicit user instruction: a fixed
# 6-digit, all-numeric, system-assigned code per entity, never caller-
# supplied or editable. The leading digit(s) identify which master a
# code belongs to; the remaining digits are that master's own
# per-organisation sequence, assigned by each entity's own
# _generate_*_code (existing count + 1, retried against IdFormat's own
# uniqueness under IntegrityError -- the pattern first established by
# Customer/Supplier below, now applied to every master). Superseds the
# letter-prefixed PRODUCT_ID/MATERIAL_ID/CUSTOMER_ID/SUPPLIER_ID shapes
# this file previously defined.
RAW_MATERIAL_CODE = IdFormat(prefix="1", digits=5)
PRODUCT_CODE = IdFormat(prefix="2", digits=5)
CUSTOMER_ID = IdFormat(prefix="3", digits=5)
SUPPLIER_ID = IdFormat(prefix="4", digits=5)
CATEGORY_CODE = IdFormat(prefix="5", digits=5)

# Small, effectively-fixed-size masters (JDK has 1 of each today) share a
# distinct "0000-prefixed" shape rather than a full 5-digit sequence --
# a single free digit each, so at most 9 records per type (IdFormat's
# own sequence floor is 1, not 0, so the range is 1-9, not "0-9 / cap of
# 10" literally -- reusing this existing, already-tested utility as-is
# rather than forking its invariant for one narrower shape).
PRODUCTION_LINE_CODE = IdFormat(prefix="00001", digits=1)
MACHINE_CODE = IdFormat(prefix="00002", digits=1)
WAREHOUSE_CODE = IdFormat(prefix="00003", digits=1)
